services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
  DISK2_SIZE: "32G"
  DISK3_SIZE: "64G"
  - ./example2:/storage2
  - ./example3:/storage3
    restart: always
    stop_grace_period: 2m
environment:
  USERNAME: "Aeron Uno"
  PASSWORD: "uno1234567890"
environment:
  DHCP: "Y"
devices:
  - /dev/vhost-net
device_cgroup_rules:
  - 'c *:* rwm'
